# Generated by Django 3.2.7 on 2021-09-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vit_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register_form',
            new_name='register_forms',
        ),
    ]
